<?php

function work_todo_menu() {
  $items['todo'] = array(
    'title' => 'To Do',
    'page callback' => 'work_todo_page',
    'access callback' => TRUE,
  );
  
  $items['todo/%'] = array(
    'title' => 'To Do',
    'page callback' => 'work_todo_page_user',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );
  
  
  $items['todo/done/%'] = array(
    'title' => 'To Do',
    'page callback' => 'work_todo_done',
    'page arguments' => array(2),
    'access callback' => TRUE,
  );
  
  $items['todo/do-later/%'] = array(
    'title' => 'To Do',
    'page callback' => 'work_todo_do_later',
    'page arguments' => array(2),
    'access callback' => TRUE,
  );
  
  $items['todo/do-sooner/%'] = array(
    'title' => 'To Do',
    'page callback' => 'work_todo_do_sooner',
    'page arguments' => array(2),
    'access callback' => TRUE,
  );
  
  $items['todo/do-tomorrow/%'] = array(
    'title' => 'To Do',
    'page callback' => 'work_todo_do_tomorrow',
    'page arguments' => array(2),
    'access callback' => TRUE,
  );
  
  $items['todo/do-today/%'] = array(
    'title' => 'To Do',
    'page callback' => 'work_todo_do_today',
    'page arguments' => array(2),
    'access callback' => TRUE,
  );

  $items['todo/add'] = array(
    'title' => 'To Do Add',
    'page callback' => 'work_todo_add',
    'access callback' => TRUE,
  );
  
  $items['todo/add/%'] = array(
    'title' => 'To Do Add',
    'page callback' => 'work_todo_add_user',
    'page arguments' => array(2),
    'access callback' => TRUE,
  );
  
  $items['todo/%/cli'] = array(
    'title' => 'To Do',
    'page callback' => 'work_todo_cli',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );
  
  

  return $items;
}

function work_todo_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['todo'] = array(
    'template' => 'todo',
    'variables' => array('data' => null, 'data_done' => null),
    'path' => drupal_get_path('module', 'work_todo') . '/templates',
   );

  return $theme;
}

function work_todo_add_user($uid) {
  $result = db_query("UPDATE {field_data_field_priority} SET field_priority_value = (field_priority_value + 1)}");

  $node = new stdClass();
  $node->title = $_POST['todo'];
  $node->type = "todo";
  node_object_prepare($node); 

  $node->language = LANGUAGE_NONE;
  $node->uid = $uid;
  $node->status = 1;
  
  $node->field_assigned_to[LANGUAGE_NONE][0]['uid'] = $uid;
  $node->field_status[LANGUAGE_NONE][0]['value'] = 0;
  $node->field_date[LANGUAGE_NONE][0]['value'] = date('Y-m-d 01:00:00');
  $node->field_priority[LANGUAGE_NONE][0]['value'] = 1;

  $node = node_submit($node);
  node_save($node);

  drupal_set_message("TODO added");
  drupal_goto("todo");
}

function work_todo_add() {
  global $user;

  $result = db_query("UPDATE {field_data_field_priority} SET field_priority_value = (field_priority_value + 1)}");

  $node = new stdClass();
  $node->title = $_POST['todo'];
  $node->type = "todo";
  node_object_prepare($node); 

  $node->language = LANGUAGE_NONE;
  $node->uid = $user->uid;
  $node->status = 1;
  
  $node->field_assigned_to[LANGUAGE_NONE][0]['uid'] = $user->uid;
  $node->field_status[LANGUAGE_NONE][0]['value'] = 0;
  $node->field_date[LANGUAGE_NONE][0]['value'] = date('Y-m-d 01:00:00');
  $node->field_priority[LANGUAGE_NONE][0]['value'] = 1;

  $node = node_submit($node);
  node_save($node);

  drupal_set_message("TODO added");
  drupal_goto("todo");
}

function work_todo_page() {
  global $user;

  $result = db_query("  SELECT nid 
                        FROM {node} n 
                        INNER JOIN {field_data_field_assigned_to} u ON n.nid = u.entity_id 
                        INNER JOIN {field_data_field_priority} p ON n.nid = p.entity_id 
                        INNER JOIN {field_data_field_todo_status} s ON n.nid = s.entity_id 
                        WHERE n.type = 'todo' AND u.bundle = 'todo' AND s.field_todo_status_value = 0 AND s.bundle = 'todo' AND u.field_assigned_to_uid = :uid
                        ORDER BY p.field_priority_value", array(':uid' => $user->uid));

  $nodes = array();
  foreach ($result as $r) {
    $nodes[] = node_load($r->nid); 
  }
  
  $result = db_query("  SELECT nid 
                        FROM {node} n 
                        INNER JOIN {field_data_field_assigned_to} u ON n.nid = u.entity_id 
                        INNER JOIN {field_data_field_priority} p ON n.nid = p.entity_id 
                        INNER JOIN {field_data_field_todo_status} s ON n.nid = s.entity_id 
                        WHERE n.type = 'todo' AND u.bundle = 'todo' AND s.field_todo_status_value = 1 AND s.bundle = 'todo' AND u.field_assigned_to_uid = :uid
                        ORDER BY n.changed DESC
                        LIMIT 25", array(':uid' => $user->uid));

  $nodes_done = array();
  foreach ($result as $r) {
    $nodes_done[] = node_load($r->nid); 
  }

  return theme('todo', array('data' => $nodes, 'data_done' => $nodes_done));
}

function work_todo_page_user($uid) {
  $result = db_query("  SELECT nid 
                        FROM {node} n 
                        INNER JOIN {field_data_field_assigned_to} u ON n.nid = u.entity_id 
                        INNER JOIN {field_data_field_priority} p ON n.nid = p.entity_id 
                        INNER JOIN {field_data_field_todo_status} s ON n.nid = s.entity_id 
                        WHERE n.type = 'todo' AND u.bundle = 'todo' AND s.field_todo_status_value = 0 AND s.bundle = 'todo' AND u.field_assigned_to_uid = :uid
                        ORDER BY p.field_priority_value", array(':uid' => $uid));

  $nodes = array();
  foreach ($result as $r) {
    $nodes[] = node_load($r->nid); 
  }
  
  $result = db_query("  SELECT nid 
                        FROM {node} n 
                        INNER JOIN {field_data_field_assigned_to} u ON n.nid = u.entity_id 
                        INNER JOIN {field_data_field_priority} p ON n.nid = p.entity_id 
                        INNER JOIN {field_data_field_todo_status} s ON n.nid = s.entity_id 
                        WHERE n.type = 'todo' AND u.bundle = 'todo' AND s.field_todo_status_value = 1 AND s.bundle = 'todo' AND u.field_assigned_to_uid = :uid
                        ORDER BY n.changed DESC
                        LIMIT 25", array(':uid' => $uid));

  $nodes_done = array();
  foreach ($result as $r) {
    $nodes_done[] = node_load($r->nid); 
  }

  return theme('todo', array('data' => $nodes, 'data_done' => $nodes_done));
}

function work_todo_done($nid) {
  $node = node_load($nid);
  $node->field_todo_status[LANGUAGE_NONE][0]['value'] = 1;
  node_save($node);

  drupal_goto('todo');
}

function work_todo_do_later($nid) {
  global $user;

  $result = db_query("SELECT nid FROM {node} WHERE type = 'todo' AND uid = {$user->uid}");

  foreach ($result as $r) {
    $node = node_load($r->nid);

    if (($node->field_todo_status['und'][0]['value'] == 0) && ($node->field_date[LANGUAGE_NONE][0]['value'] <= date('Y-m-d 24:59:59'))) {
      $todo[$r->nid] = $node->field_priority['und'][0]['value'];
    }
  }
  
  asort($todo);

  $count = 0;
  foreach ($todo as $k => $v) {
    $count += 1;
    $todo[$k] = $count;
    if ($k == $nid) {
      $current_sort = $count;
    }
  }

  $todo = array_flip($todo);
 
  if (isset($todo[($current_sort + 1)])) {
    $todo[$current_sort] = $todo[($current_sort + 1)];
    $todo[($current_sort + 1)] = $nid;
  }
  
  foreach ($todo as $k => $v) {
    $node = node_load($v);
    $node->field_priority['und'][0]['value'] = $k;
    node_save($node);
  }

  drupal_goto('todo');
}

function work_todo_do_sooner($nid) {
  global $user;

  $result = db_query("SELECT nid FROM {node} WHERE type = 'todo' AND uid = {$user->uid}");

  foreach ($result as $r) {
    $node = node_load($r->nid);

    if (($node->field_todo_status['und'][0]['value'] == 0) && ($node->field_date[LANGUAGE_NONE][0]['value'] <= date('Y-m-d 24:59:59'))) {
      $todo[$r->nid] = $node->field_priority['und'][0]['value'];
    }
  }
  
  asort($todo);

  $count = 0;
  foreach ($todo as $k => $v) {
    $count += 1;
    $todo[$k] = $count;
    if ($k == $nid) {
      $current_sort = $count;
    }
  }

  $todo = array_flip($todo);
 
  if (isset($todo[($current_sort - 1)])) {
    $todo[$current_sort] = $todo[($current_sort - 1)];
    $todo[($current_sort - 1)] = $nid;
  }
  
  foreach ($todo as $k => $v) {
    $node = node_load($v);
    $node->field_priority['und'][0]['value'] = $k;
    node_save($node);
  }

  drupal_goto('todo');
}

function work_todo_do_tomorrow($nid) {
  $node = node_load($nid);
  $node->field_date[LANGUAGE_NONE][0]['value'] = date('Y-m-d 01:00:00', (time() + 86400));
  $node->field_priority['und'][0]['value'] = 999;
  node_save($node);

  drupal_goto('todo');
}

function work_todo_do_today($nid) {
  $node = node_load($nid);
  $node->field_date[LANGUAGE_NONE][0]['value'] = date('Y-m-d 01:00:00');
  node_save($node);

  work_todo_do_later($nid);
}

function work_todo_cli($uid) {
  $result = db_query("  SELECT nid 
                        FROM {node} n 
                        INNER JOIN {field_data_field_date} d ON n.nid = d.entity_id 
                        INNER JOIN {field_data_field_assigned_to} u ON n.nid = u.entity_id 
                        INNER JOIN {field_data_field_priority} p ON n.nid = p.entity_id 
                        INNER JOIN {field_data_field_todo_status} s ON n.nid = s.entity_id 
                        WHERE n.type = 'todo' AND u.bundle = 'todo' AND s.field_todo_status_value = 0 AND s.bundle = 'todo' AND u.field_assigned_to_uid = :uid AND d.field_date_value <= '".date('Y-m-d 23:59:59')."'
                        GROUP BY nid
                        ORDER BY substr(d.field_date_value,0,11),  p.field_priority_value", array(':uid' => $uid));


  $todo = '';
  foreach ($result as $r) {
    $node = node_load($r->nid); 
    $todo .= "<span style='color:green'>({$node->nid}) {$node->title}</span><br />";
  }

  $todo .= "<hr style='color:blue; border-color:blue;' />";

  $result = db_query("  SELECT nid 
                        FROM {node} n 
                        INNER JOIN {field_data_field_date} d ON n.nid = d.entity_id 
                        INNER JOIN {field_data_field_assigned_to} u ON n.nid = u.entity_id 
                        INNER JOIN {field_data_field_priority} p ON n.nid = p.entity_id 
                        INNER JOIN {field_data_field_todo_status} s ON n.nid = s.entity_id 
                        WHERE n.type = 'todo' AND u.bundle = 'todo' AND s.field_todo_status_value = 0 AND s.bundle = 'todo' AND u.field_assigned_to_uid = :uid AND d.field_date_value > '".date('Y-m-d 23:59:59')."'
                        GROUP BY nid
                        ORDER BY substr(d.field_date_value,0,11),  p.field_priority_value", array(':uid' => $uid));

  foreach ($result as $r) {
    $node = node_load($r->nid); 
    $todo .= "<span style='color:yellow;'>({$node->nid}) {$node->title}</span><br />";
  }
  
  $todo .= "<hr style='color:blue; border-color:blue;' />";

  $result = db_query("  SELECT nid 
                        FROM {node} n 
                        INNER JOIN {field_data_field_date} d ON n.nid = d.entity_id 
                        INNER JOIN {field_data_field_assigned_to} u ON n.nid = u.entity_id 
                        INNER JOIN {field_data_field_priority} p ON n.nid = p.entity_id 
                        INNER JOIN {field_data_field_todo_status} s ON n.nid = s.entity_id 
                        WHERE n.type = 'todo' AND u.bundle = 'todo' AND s.field_todo_status_value = 1 AND s.bundle = 'todo' 
                        GROUP BY nid
                        ORDER BY n.changed DESC
                        LIMIT 5", array(':uid' => $uid));

  foreach ($result as $r) {
    $node = node_load($r->nid); 
    $todo .= "<span style='color:red;'>({$node->nid}) <span style='text-decoration:line-through;'>{$node->title}</span></span><br />";
  }
  
  print $todo;
  exit;
}
