<?php

function work_timesheet_menu() {
  $items['timesheet'] = array(
    'title' => 'Timesheet',
    'page callback' => 'work_timesheet',
    'access callback' => TRUE,
  );

  return $items;
}

function work_timesheet_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['timesheet'] = array(
    'template' => 'timesheet',
    'path' => drupal_get_path('module', 'work_timesheet'),
    'variables' => array('table' => null),
   );

  return $theme;
}

function work_timesheet() {
  global $user;
  $group_by = null;
  $params = drupal_get_query_parameters();
  if(!isset($params["start_date"]) && !isset($params["end_date"])) {
    $start_date = date("Y-m-00 00:00:00");
    $end_date = date("Y-m-32 00:00:00");
  } else {
    $start_date = date('Y-m-d 00:00:00',strtotime($params["start_date"]));
    $end_date = date('Y-m-d 24:00:00',strtotime($params["end_date"]));
  }
  //var_dump($params);
  //print_r($start_date); print_r($end_date); exit;
  $header = array('task', 'price', 'hours', 'total');
  $table = theme('table', array('header'=> $header, 'rows' => work_timesheet_get_date($start_date, $end_date, $group_by)));
  return theme('timesheet', array('table' => $table));
}

function work_timesheet_get_date($start_date, $end_date, $group_by) {
  global $user;
  $query = db_select('node', 'n');
  $query->addField('n', 'nid');
  $query->addField('n', 'title');
  $query->addField('ft', 'field_time_value');
  $query->addField('u', "'field_user_uid'");
  $query->addField('d', 'field_date_value');
  $query->addField('h', 'field_hours_value');
  $query->addField('fd', 'field_description_value');
  $query->join('field_data_field_time', 'ft', 'n.nid = ft.entity_id');
  $query->leftJoin('field_data_field_user', 'u', 'u.entity_id = ft.field_time_value');
  $query->leftJoin('field_data_field_date', 'd', 'd.entity_id = ft.field_time_value');
  $query->leftJoin('field_data_field_hours', 'h', 'h.entity_id = ft.field_time_value');
  $query->leftJoin('field_data_field_description', 'fd', 'fd.entity_id = ft.field_time_value');
  $query->condition('n.type', 'task');
  $results = $query->execute();
  //print '<pre>'; print_r($results); exit;      

  $rows = array();
  foreach ($results as $r) {
    $rows[] = array($r->title, 20, $r->field_hours_value, (20 * $r->field_hours_value));
  }
  return $rows;
}