<?php

/**
 * Hook_menu.
 */
function work_log_menu(){
  $items['work-log/ajax/get-log-by-nid/%'] = array(
    'title' => "Work Log",
    'page callback' => 'work_log_ajax_get_log',
    'access callback' => TRUE,
    'page arguments' => array(3),
  );

  $items['work-log/ajax/get-log-by-todo-eid/%'] = array(
    'title' => "Work Log",
    'page callback' => 'work_log_ajax_get_log_by_todo_eid',
    'access callback' => TRUE,
    'page arguments' => array(3),
  );

  return $items;
}


/**
 * This function creates a log_entry node which refernces to the given node id
 */
function work_log_create_log_entry($node_nid, $log_title, $log_message) {
  global $user;

  $log_node = new stdClass();
  $log_node->title = $log_title;
  $log_node->type = "log_entry";
  node_object_prepare($log_node);
  $log_node->language = LANGUAGE_NONE;
  $log_node->status = 1;
  $log_node->promote = 0;
  $log_node->comment = 0;

  // Set user
  $log_node->uid = $user->uid;

  // Set body
  $log_node->body['und'][0] = array(
    'value' => $log_message,
    'format' => 'full_html');
  // Set node reference
  $parent_type = db_query("
    SELECT type FROM {node}
    WHERE nid = :nid",
    array(":nid" => $node_nid))->fetchField();
  $log_node->{'field_'.$parent_type}['und'][0]['nid'] = $node_nid;

  $log_node = node_submit($log_node); // Prepare node for saving
  node_save($log_node);
}

/**
 * Returns the rendered html markup of the log.
 */
function work_log_view($node_nid) {
  $node_type = db_query("
    SELECT type FROM {node} WHERE nid = :nid",
    array(":nid" => $node_nid))->fetchField();

  $logs = db_query("
    SELECT n.nid FROM {node} AS n
    INNER JOIN {field_data_field_$node_type} AS f
    ON f.entity_id = n.nid
    WHERE f.field_".$node_type."_nid = :nid
    AND f.bundle = 'log_entry'
    ORDER BY n.created DESC", array(":nid" => $node_nid))->fetchAll();


  $rendered_log = "";


  foreach($logs as $log) {
    $n = node_load($log->nid);
    //$rendered_log.= print_r($n, TRUE);
    $content = node_view($n);
    $rendered_log .= render($content);
  }

  return $rendered_log;

}

/**
 * Returns the rendered html mark up of the log via ajax call.
 */
function work_log_ajax_get_log($nid) {
  echo work_log_view($nid);
}


function work_log_ajax_get_log_by_todo_eid($eid) {
  $nid = db_query("
    SELECT entity_id FROM field_data_field_to_do
    WHERE field_to_do_value = :eid", array(":eid" => $eid))->fetchField();
  work_log_ajax_get_log($nid);
}
