<?php

function work_task_menu() {
  $items['tasks/estimate/%'] = array(
    'title' => 'estimate',
    'page callback' => 'work_task_estimate',
    'page arguments' => array(2),
    'access callback' => TRUE,
  );
  
  $items['tasks/update-todo/%'] = array(
    'title' => 'update todo',
    'page callback' => 'work_task_update_todo',
    'page arguments' => array(2),
    'access callback' => TRUE,
  );
  
  $items['tasks/update-todo/add'] = array(
    'title' => 'add todo',
    'page callback' => 'work_task_update_todo_add',
    'access callback' => TRUE,
  );
  
  $items['tasks/update-status/%/%'] = array(
    'title' => 'update status',
    'page callback' => 'work_task_update_status',
    'page arguments' => array(2, 3),
    'access callback' => TRUE,
  );
  
  $items['tasks/update-assigned/%/%'] = array(
    'title' => 'update assigned',
    'page callback' => 'work_task_update_assigned',
    'page arguments' => array(2, 3),
    'access callback' => TRUE,
  );

  $items['tasks/update-users/add/%/%'] = array(
    'title' => 'update users add',
    'page callback' => 'work_task_update_users_add',
    'page arguments' => array(3, 4),
    'access callback' => TRUE,
  );
  
  $items['tasks/update-schedule/add'] = array(
    'title' => 'add schedule',
    'page callback' => 'work_task_update_schedule',
    'access callback' => TRUE,
  );
  
  $items['tasks/update-schedule/delete/%/%'] = array(
    'title' => 'update schedule',
    'page callback' => 'work_task_update_schedule_delete',
    'page arguments' => array(3, 4),
    'access callback' => TRUE,
  );
  
  $items['tasks/update-time/add'] = array(
    'title' => 'add time',
    'page callback' => 'work_task_update_time',
    'access callback' => TRUE,
  );
  
  $items['tasks/update-time/delete/%/%'] = array(
    'title' => 'update time',
    'page callback' => 'work_task_update_time_delete',
    'page arguments' => array(3, 4),
    'access callback' => TRUE,
  );
  
  $items['tasks/update-comment/add'] = array(
    'title' => 'update comments',
    'page callback' => 'work_task_update_comment',
    'access callback' => TRUE,
  );
  
  $items['tasks/update-credentials/add'] = array(
    'title' => 'update credentials',
    'page callback' => 'work_task_update_credentials',
    'access callback' => TRUE,
  );
  
  $items['tasks/update-assets/add'] = array(
    'title' => 'update assets',
    'page callback' => 'work_task_update_assets',
    'access callback' => TRUE,
  );
  
  $items['tasks/update-resources/add'] = array(
    'title' => 'update resources',
    'page callback' => 'work_task_update_resources',
    'access callback' => TRUE,
  );

  $items['tasks/add/%'] = array(
    'title' => 'Add Tasks',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('work_task_add_task', 2),
    'access callback' => TRUE,
  );

  return $items;
}

function work_task_add_task($form, $form_state, $project) {
  $form['#tree'] = TRUE;
  $form['#attributes']['enctype'] = 'multipart/form-data';

  $p = node_load($project);

  $form['title'] = array(
    '#type' => 'item',
    '#markup' => "<h3>Adding task for <strong>{$p->title}</strong></h3>",
  );

  $form['project'] = array(
    '#type' => 'hidden',
    '#value' => $project,
  );

  $form['task'] = array(
    '#title' => 'Task',
    '#type' => 'textfield',
  );

  global $user;

  $users = db_query("SELECT uid, name FROM {users} WHERE uid IN (SELECT uid FROM {users_roles} WHERE rid IN (3, 4, 5))");

  $assigned_to = array();
  foreach ($users as $u) {
    $assigned_to[$u->uid] = $u->name;
  }

  $form['assigned_to'] = array(
    '#title' => 'Assigned To',
    '#type' => 'select',
    '#options' => $assigned_to,
    '#default_value' => $user->uid,
  );

  $form['due_date'] = array(
    '#type' => 'date_popup',
    '#date_format' => 'Y-m-d',
    '#date_year_range' => '-3:+3',
    '#title' => 'Due Date',
  );

  $form['description'] = array(
    '#title' => 'Description',
    '#type' => 'textarea',
  );

  // --------------- Add more text box starts  ------------------------------

  $form['action_items']['action_items_fieldset'] = array(
    '#type' => 'fieldset',
    '#title' => t('Action Items'),
    '#prefix' => '<div id="action-items-wrapper">',
    '#suffix' => '</div>',
  );

  if (empty($form_state['num_items'])) {
    $form_state['num_items'] = 1;
  }

  for ($i = 0; $i < $form_state['num_items']; $i++) {

  $form['action_items']['action_items_fieldset']['items'][$i] = array(
    '#type' => 'textfield',
    '#attributes' => array('multiple' => 'multiple'),
    );
  }

  $form['action_items']['action_items_fieldset']['add_action_item'] = array(
      '#type' => 'submit',
      '#value' => t('Add Action Item'),
      '#submit' => array('action_add_one'),
      '#ajax' => array(
        'callback' => 'action_add_one_callback',
        'wrapper' => 'action-items-wrapper',
      ),
  );

  // ---------------  Add more text box ends ---------------------------------

  $form['example_entry']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}

function work_task_add_task_submit($form, &$form_state) {
  $v = $form_state['values'];

  global $user;

  $node = new stdClass();
  $node->title = $v['task'];
  $node->type = 'task';
  node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
  $node->language = LANGUAGE_NONE; // Or e.g. 'en' if locale is enabled
  $node->uid = $user->uid; 
  $node->status = 1; 
  $node->promote = 0; 
  $node->comment = 0; 

  $node->field_status['und'][0]['tid'] = 1;
  
  $node->field_project['und'][0]['nid'] = $v['project'];

  $node->field_assigned_to['und'][0]['uid'] = $v['assigned_to'];

  $node->field_users['und'][0]['uid'] = $v['assigned_to'];

  if ($user->uid != $v['assigned_to']) {
    $node->field_users['und'][1]['uid'] = $user->uid;
  }

  $node->field_due_date['und'][0]['value'] = $v['due_date'] . ' 00:00:00';
  
  node_save($node);

  module_load_include('inc', 'entity', 'includes/entity.controller');

  foreach($v['action_items']['action_items_fieldset']['items'] as $i) { 
    $fc = array();  

    $fc['field_name'] = 'field_to_do';

    $fc['field_description']['und'][0]['value'] = $i;  

    $entity = entity_create('field_collection_item', $fc);
    $entity->setHostEntity('node', $node);
    $entity->save();
  }

  node_save($node);

  work_log_create_log_entry($v['project'], "Task Added", "Task Added: " . l($node->title, 'node/' . $node->nid));
  drupal_set_message("Task Added: " . l($node->title, 'node/' . $node->nid));

  drupal_goto('<front>');
}

function action_add_one($form, &$form_state) {
  if (!isset($form_state['num_items'])) {
    $form_state['num_items'] = 0;
    $form_state['num_items']++;
  }

  $form_state['num_items']++;
  $form_state['rebuild'] = TRUE;
} 

function action_add_one_callback($form, &$form_state) {
  return $form['action_items']['action_items_fieldset'];
}



function work_task_estimate($nid) {
  $node = node_load($nid);

  $content = node_view($node);

  print render($content['field_estimate']);
  
  drupal_exit();
}

function work_task_update_time_delete($nid, $fcid) {


  entity_delete_multiple('field_collection_item', array($fcid));

  $node = node_load($nid);

  foreach ($node->field_time['und'] as $k => $s) {
    if ($s['value'] == $fcid) {
      unset($node->field_time['und'][$k]);
    }
  }

  node_save($node);
  
  $content = node_view($node);
  print render($content['field_time']);
  
  drupal_exit();
}

function work_task_update_time() {
  $data = array();
  parse_str($_POST['data'], $data);

  module_load_include('inc', 'entity', 'includes/entity.controller');

  $fc = array();  

  $fc['field_name'] = 'field_time';
  $fc['field_date']['und'][0]['value'] = date('Y-m-d H:i:s', strtotime($data['date']));  
 
  global $user;
  $fc['field_user']['und'][0]['uid'] = $user->uid;

  $fc['field_hours']['und'][0]['value'] = $data['hours'];
  $fc['field_description']['und'][0]['value'] = $data['description'];

  $node = node_load($data['nid']);

  $entity = entity_create('field_collection_item', $fc);
  $entity->setHostEntity('node', $node);
  $entity->save();

  $content = node_view($node);
  print render($content['field_time']);
  
  drupal_exit();
}

function work_task_update_schedule_delete($nid, $fcid) {
  // get info for log entry
  $fc = entity_load('field_collection_item', array($fcid));
  $fc = array_shift($fc);
  $date = substr($fc->field_date['und'][0]['value'], 0 ,10);
  $u = db_query("
    SELECT name FROM {users} WHERE uid = :uid",
    array(":uid" => $fc->field_user['und'][0]['uid']))->fetchField();
  $time = "";
  foreach ($fc->field_schedule_time['und'] as $v){
    $time .= $v['value'].", ";
  }
  $time = rtrim($time, ", ");
  work_log_create_log_entry($nid, "Scheduled Time Deleted",
    "Scheduled time deleted:<br/>Date: ".$date."<br/>Time: ".$time. "<br/>Created by ". $u);

  // Delete actual field collection
  entity_delete_multiple('field_collection_item', array($fcid));

  $node = node_load($nid);

  foreach ($node->field_schedule['und'] as $k => $s) {
    if ($s['value'] == $fcid) {
      unset($node->field_schedule['und'][$k]);
    }
  }

  node_save($node);
  
  $content = node_view($node);
  print render($content['field_schedule']);
  
  drupal_exit();
}

function work_task_update_schedule() {
  $data = array();
  parse_str($_POST['data'], $data);

  module_load_include('inc', 'entity', 'includes/entity.controller');

  $fc = array();  

  $fc['field_name'] = 'field_schedule';
  $fc['field_date']['und'][0]['value'] = date('Y-m-d H:i:s', strtotime($data['date']));  
 
  $time_string = "";
  foreach ($data['time'] as $t) {
    $fc['field_schedule_time']['und'][]['value'] = $t;
    $time_string .= $t .", ";
  } 
  
  $time_string = rtrim($time_string, ", ");
  global $user;
  $fc['field_user']['und'][0]['uid'] = $user->uid;

  $node = node_load($data['nid']);

  $entity = entity_create('field_collection_item', $fc);
  $entity->setHostEntity('node', $node);
  $entity->save();



  work_log_create_log_entry($node->nid, "Scheduled Time Updated",
    "Scheduled time updated:<br/>Date: ".
    substr($fc['field_date']['und'][0]['value'], 0, 10) .
    "<br/>Time: " . $time_string . "<br/>Created by " . $user->name);
  
  $content = node_view($node);
  print render($content['field_schedule']);
  
  drupal_exit();
}

function work_task_update_status($nid, $tid) {
  $node = node_load($nid);

  $original_status = db_query("
    SELECT name FROM {taxonomy_term_data}
    WHERE tid = :tid", array(":tid" => $node->field_status['und'][0]['tid']))->fetchField();

  $node->field_status['und'][0]['tid'] = $tid;
  $new_status = db_query("
    SELECT name FROM {taxonomy_term_data}
    WHERE tid = :tid", array(":tid" => $tid))->fetchField();
  node_save($node);
  
  work_log_create_log_entry($nid, "Status Updated",
    "Status changed from <strong>" .
    $original_status . "</strong> to <strong>" . $new_status . "</strong>");
  
}

function work_task_update_assigned($nid, $uid) {
  $node = node_load($nid);
  $node->field_assigned_to['und'][0]['uid'] = $uid;
  node_save($node);

  $u = db_query("SELECT name FROM {users} WHERE uid = :uid", array(":uid" => $uid))->fetchField();
  work_log_create_log_entry($node->nid,"Assignee changed",
    "Task assigned to <strong>" . $u ."</strong>");
}

function work_task_update_users_add($nid, $uid) {
  $node = node_load($nid);

  $node->field_users['und'][]['uid'] = $uid;

  node_save($node);

  $u = db_query("SELECT name FROM {users} WHERE uid = :uid", array(":uid" => $uid))->fetchField();

  work_log_create_log_entry($node->nid,"User Added",
    "New user <strong>" . $u . "</strong> added to the task");
  
  $content = node_view($node);
  print render($content['field_users']);
  
  drupal_exit();
}

function work_task_update_todo($id) {
  $collection = entity_load('field_collection_item', array($id));
  $todo = array_pop($collection);

  $nid = db_query("
    SELECT entity_id FROM {field_data_field_task_todo}
    WHERE field_task_todo_value = :fc_id", array(":fc_id" => $id))->fetchField();

  global $user;

  if ($todo->field_todo_status['und'][0]['value'] == 1) {
    $todo->field_user['und'][0]['uid'] = null;
    $todo->field_todo_status['und'][0]['value'] = 0;

  } else {
    $todo->field_user['und'][0]['uid'] = $user->uid;
    $todo->field_todo_status['und'][0]['value'] = 1;
  }
  entity_save('field_collection_item', $todo);

  work_log_create_log_entry($nid, "Todo status changed",
      "Todo status changed to <strong>".
      ( $todo->field_todo_status['und'][0]['value'] == 0 ? "Unfinished" : "finished" ).
      "</strong> by ". $user->name."<br/>Todo description:<br/>".$todo->field_description['und'][0]['value']);
  
  
}

function work_task_update_todo_add() {
  $data = array();
  parse_str($_POST['data'], $data);

  module_load_include('inc', 'entity', 'includes/entity.controller');

  $fc = array();

  $fc['field_name'] = 'field_to_do';
  $fc['field_description']['und'][0]['value'] = $data['todo'];  
 
  $node = node_load($data['nid']);

  $entity = entity_create('field_collection_item', $fc);
  $entity->setHostEntity('node', $node);
  $entity->save();
  
  $node = node_load($data['nid']);

  global $user;
  work_log_create_log_entry($node->nid, "New Todo added",
    "New Todo item added by " . $user->name .
    "<br/>Todo description:<br/>".$entity->field_description['und'][0]['value']);
  
  $content = node_view($node);
  print render($content['field_to_do']);
  
  
  drupal_exit();
}

function work_task_update_comment() {
  $data = array();
  parse_str($_POST['data'], $data);

  module_load_include('inc', 'entity', 'includes/entity.controller');

  $fc = array();  

  $fc['field_name'] = 'field_comments';


  global $user;
  $fc['field_user']['und'][0]['uid'] = $user->uid;

  $fc['field_date_time']['und'][0]['value'] = date('Y-m-d H:i:s');  
 

  $fc['field_title']['und'][0]['value'] = $data['title'];
  $fc['field_comment_description']['und'][0]['value'] = $data['description'];

  $node = node_load($data['nid']);

  $entity = entity_create('field_collection_item', $fc);
  $entity->setHostEntity('node', $node);
  $entity->save();

  global $user;
  work_log_create_log_entry($node->nid, "New comment added",
    "New comment added by " . $user->name .
    "<br/>Comment:<br/>".$entity->field_title['und'][0]['value']);

  $content = node_view($node);
  print render($content['field_comments']);
  
  drupal_exit();
}

function work_task_update_credentials() {
  $data = array();
  parse_str($_POST['data'], $data);

  module_load_include('inc', 'entity', 'includes/entity.controller');

  $fc = array();  

  $fc['field_name'] = 'field_credentials';

  $fc['field_description']['und'][0]['value'] = $data['description'];
  $fc['field_path']['und'][0]['value'] =        $data['path'];
  $fc['field_username']['und'][0]['value'] =    $data['username'];
  $fc['field_password']['und'][0]['value'] =    $data['password'];


  $node = node_load($data['nid']);

  $entity = entity_create('field_collection_item', $fc);
  $entity->setHostEntity('node', $node);
  $entity->save();

  global $user;
  work_log_create_log_entry($node->nid, "Credentials updated",
    "Credentials updated by " . $user->name .
    "<br/>Credentials description: ".$entity->field_description['und'][0]['value']);

  $content = node_view($node);
  print render($content['field_credentials']);
  
  drupal_exit();
}

function work_task_update_assets() {

  module_load_include('inc', 'entity', 'includes/entity.controller');

  $fc = array();  

  $fc['field_name'] = 'field_assets';

  $fc['field_description']['und'][0]['value'] = $_POST['asset'];

  $file = file_get_contents($_FILES['file']['tmp_name']);

  $file_upload = file_save_data($file, 'public://' . $_FILES['file']['name'], FILE_EXISTS_RENAME);

  $file_upload->display = 1;

  $fc['field_asset']['und'][] = (array) $file_upload;

  $node = node_load($_POST['nid']);

  $entity = entity_create('field_collection_item', $fc);
  $entity->setHostEntity('node', $node);
  $entity->save();

  drupal_set_message("Asset added");

  global $user;
  work_log_create_log_entry($node->nid, "Asset added",
    "Asset added by " . $user->name .
    "<br/>File description: ".$entity->field_description['und'][0]['value']);

  drupal_goto('node/' . $node->nid, array('query' => array('assets' => 'TRUE')));
  drupal_exit();
}

function work_task_update_resources() {
  $data = array();
  parse_str($_POST['data'], $data);

  module_load_include('inc', 'entity', 'includes/entity.controller');

  $fc = array();  

  $fc['field_name'] = 'field_resources';

  $fc['field_description']['und'][0]['value'] = $data['resource'];
  $fc['field_url']['und'][0]['url'] = $data['url'];
  $fc['field_url']['und'][0]['title'] = $data['url'];
  $fc['field_url']['und'][0]['attributes']['target'] = '_blank';


  $node = node_load($data['nid']);

  $entity = entity_create('field_collection_item', $fc);
  $entity->setHostEntity('node', $node);
  $entity->save();

  global $user;
  work_log_create_log_entry($node->nid, "Resource added",
    "Resource added by " . $user->name .
    "<br/>Resource description: ".$entity->field_description['und'][0]['value']);


  $content = node_view($node);

  print render($content['field_resources']);
  
  drupal_exit();
}


function custom_task_ajax_add_action($form, $form_state) {
  return $form['actions'];
}

function work_task_progress($nid) {
  $node = node_load($nid);

  if (isset($node->field_to_do['und'])) {
    $count = count($node->field_to_do['und']);
    $done = 0;

    foreach($node->field_to_do['und'] as $t) {
      $e = entity_load('field_collection_item', array($t['value']));
      $fc = array_pop($e);  

      if ($fc->field_todo_status['und'][0]['value'] == 1) {
        $done += 1;
      }
    }

     return floor($done / $count * 100) . '%';
  } 

  else {
    if (($node->field_status['und'][0]['tid'] == 6) || ($node->field_status['und'][0]['tid'] == 7)) {
      return '100%';
   } else {
      return '0%';
   }
  }
}
