<?php

function work_dashboard_init() {
  global $user;

  if ((arg(0) == 'work-dashboard') && in_array($user->uid, array(81, 82))) {
    drupal_goto('node/7656');
  }
}

/**
 * Hook_menu.
 */
function work_dashboard_menu(){
  $items['work-dashboard'] = array(
    'title' => "Dashboard",
    'page callback' => 'work_dashboard_page',
    'access callback' => TRUE,
  );

  return $items;
}

function work_dashboard_theme() {
  $theme = array();
  $theme['work_dashboard_developer'] = array(
    'template' => 'work-dashboard-developer',
    'variables' => array(
      'messages' => null,
			'todo' => null,
			'schedule' => null,
			'stories' => null,
			'sprints' => null,
			'projets' => null,
			'time' => null,),
    'path' => drupal_get_path('module', 'work_dashboard') . '/templates',
   );

  return $theme;
}

/**
 * This function sets up the dashboard page
 */
function work_dashboard_page() {
	return _work_dashboard_developer();
}

function _work_dashboard_developer() {
  global $user;

  $uid = $user->uid;

	$messages = array();

  $todo = work_todo_page_user_dashboard($uid);

	$schedule = work_schedule2_user_dashboard($uid);

  // get stories without status closed assigned to the user in an active sprint
  $result = db_query("SELECT s.entity_id as nid
                      FROM {field_data_field_status} s
                        INNER JOIN {field_data_field_assigned_to} u ON u.entity_id = s.entity_id
                      WHERE s.field_status_tid != 7
                        AND u.field_assigned_to_uid = :uid",
                      array(':uid' => $uid));

  $projects = array();
  $stories = array();
  foreach ($result as $r) {
    $story = node_load($r->nid);

    $stories[][$story->field_project['und'][0]['nid']][] = $story;

    $projects[$story->field_project['und'][0]['nid']] = node_load($story->field_project['und'][0]['nid']);
  }




//	$projects = work_project_user_dashboard($uid);

	$time = 'Data coming soon.';

	return theme('work_dashboard_developer',
                array(
                  'messages' => $messages,
                  'todo' => $todo,
                  'schedule' => $schedule,
                  'stories' => $stories,
                  'projects' => $projects,
                  'time' => $time,
                )
              );
}

