<?php

function work_schedule2_menu() {
	$items['schedule/day'] = array(
    'title' => 'Schedule - Day',
    'page callback' => 'work_schedule2',
    'access callback' => TRUE,
  );
return $items;
}

function work_schedule2_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['schedule_day'] = array(
    'template' => 'schedule_day',
    'path' => drupal_get_path('module', 'work_schedule2'),
    'variables' => array('table' => null),
   );

  return $theme;
}

function work_schedule2() {
	$sort_by = 'day';
	$data = work_schedule2_query_database();
	$sorted = sort_tables($data, $sort_by);
	$table = build_tables($sorted);
	return theme('schedule_day', array('table' => $table));
}

function work_schedule2_query_database() {
	$query = db_select('node', 'n');
	//$query->addField('s', 'field_schedule_value');
	//$query->addField('s', 'entity_id');
	//$query->addField('st', 'entity_id');
	$query->addField('st', 'field_schedule_time_value');
	//$query->addField('fd', 'entity_id');
	$query->addField('fd', 'field_date_value');
	//$query->addField('fu', 'entity_id');
	//$query->addField('fu', 'field_user_uid');
	//$query->addField('u', 'uid');
	$query->addField('u', 'name');
	$query->addField('n', 'title');
	$query->join('field_data_field_schedule', 's', 'n.nid = s.entity_id');
	$query->join('field_data_field_schedule_time', 'st', 'st.entity_id = s.field_schedule_value');
	$query->join('field_data_field_date', 'fd', 'fd.entity_id = st.entity_id');
	$query->join('field_data_field_user', 'fu', 'fu.entity_id = st.entity_id');
	$query->join('users', 'u', 'u.uid = fu.field_user_uid');
	$query->condition('n.type', 'task', '=');
	$query->condition('n.status', '1', '=');
	$data = $query->execute();
	return $data;

}

function get_header($t) {
	if($temp == 'AM') {
		$header = array("<h1>AM</h1>");
	} elseif($temp == 'PM+') {
		$header = array("<h1>Evening</h1>");
	} elseif($temp == 'PM') {
		$header = array("<h1>PM</h1>");
	}
	return $header;
}

function sort_tables($data, $sort_by) {
	if($sort_by == 'day') {
		foreach($data as $d) {
			if(date("y-m-d", strtotime("today")) == date("y-m-d", strtotime($d->field_date_value))) {
				$tables[$d->field_schedule_time_value][$d->name] = $d->title;
			}
		}
	}
	return $tables;
}

function objectToArray ($object) {
    if(!is_object($object) && !is_array($object))
        return $object;
    return array_map('objectToArray', (array) $object);
}

function build_tables($data) {
	$header = array('User', 'Task');
	foreach ($data as $key=>$val) {
		$table[] = "<h1> $key </h1>";
		foreach($val as $k=>$v) {
			$rows[] = array($k, $v);
		}
		$table[] = theme('table', array('header'=> $header, 'rows' => $rows));
	}
	return $table;
}